// Document Center strings (Spanish)
export const docsEs = {
  docsTitle: "Centro de Documentos",
  docsHome: "Obtener mis documentos",
  docsHomeSub: "ID, tarjeta del Seguro Social, acta de nacimiento, EBT y Medicaid — sin llamadas, sin papeleo",
  docsIntro:
    "Responda una sola vez. Nosotros llenamos los formularios del gobierno por usted, un navegador de Helping Hand los envía y sus documentos llegan a un quiosco cerca de usted. Nunca tiene que llamar a nadie.",
  docsSignIn: "Inicie sesión o cree una cuenta para que podamos guardar sus documentos de forma segura y avisarle cuando lleguen.",
  docsPlanCard: "Podemos empezar ahora mismo con su ID, tarjeta del Seguro Social, acta de nacimiento y beneficios.",
  docsStart: "Empezar mis documentos",
  docsMine: "Mis documentos",

  docsWhich: "¿Qué necesita?",
  docsWhichSub: "Marque todo lo que aplique. Nosotros nos encargamos del orden en que deben ir.",
  doc_ssn_card: "Tarjeta del Seguro Social",
  doc_ssn_card_sub: "Tarjeta de reemplazo. Gratis. Necesaria para trabajar y para beneficios.",
  doc_birth_cert: "Acta de nacimiento",
  doc_birth_cert_sub: "Copia certificada del estado donde nació. Necesaria para obtener una identificación.",
  doc_fl_id: "Tarjeta de identificación de Florida",
  doc_fl_id_sub: "ID estatal. Gratis con una carta de verificación de personas sin hogar. Una visita corta en persona — un navegador lo acompaña.",
  doc_benefits: "EBT, Medicaid y asistencia en efectivo",
  doc_benefits_sub: "Comida (SNAP), cobertura de salud y ayuda en efectivo a través de Florida ACCESS.",

  docsAbout: "Sobre usted",
  docsAboutSub: "Use el nombre de su acta de nacimiento, aunque use otro nombre.",
  legalFirst: "Nombre",
  legalMiddle: "Segundo nombre",
  legalLast: "Apellido(s)",
  otherNames: "Otros nombres que ha usado",
  dob: "Fecha de nacimiento",
  sex: "Sexo en su acta de nacimiento",
  sex_male: "Masculino",
  sex_female: "Femenino",
  sex_x: "X / otro",
  birthPlace: "¿Dónde nació?",
  birthCity: "Ciudad",
  birthState: "Estado",
  birthCountry: "País",

  docsParents: "Sus padres",
  docsParentsSub: "El Seguro Social y la oficina de actas de nacimiento usan esto para encontrar su registro. Puede dejarlo en blanco si no lo sabe.",
  motherName: "Nombre completo de su madre",
  motherMaiden: "Apellido de soltera de su madre",
  fatherName: "Nombre completo de su padre",

  docsSsn: "Seguro Social y ciudadanía",
  ssnKnown: "¿Sabe su número de Seguro Social?",
  ssnLast4: "Últimos 4 dígitos (solo si los sabe)",
  ssnFullLater: "Le dará el número completo a su navegador en persona. Nunca lo escriba en un quiosco.",
  usCitizen: "¿Es ciudadano de EE. UU.?",
  notCitizenNote: "No hay problema. Le ayudaremos con los documentos que sí puede obtener y le conectaremos con ayuda legal de inmigración.",

  docsHave: "¿Qué tiene ahora mismo?",
  docsHaveSub: "Cualquier papel con su nombre ayuda. Tome una foto de lo que tenga — es privada y solo su navegador puede verla.",
  havePhotoId: "Cualquier identificación con foto (aunque esté vencida)",
  haveBirthCert: "Acta de nacimiento",
  haveSsnCard: "Tarjeta del Seguro Social",
  haveOther: "Cualquier otra cosa (registro escolar, tarjeta médica, correo con su nombre, talón de pago…)",
  addPhoto: "Agregar una foto",
  photoLabel: "¿Qué es esto?",
  uploading: "Subiendo…",
  photoAdded: "Foto guardada.",
  photos: "Fotos",

  docsReach: "¿Cómo le contactamos?",
  docsReachSub: "Cada actualización llega a su bandeja en esta app y en cualquier quiosco. Si tiene teléfono, también puede agregarlo.",
  phoneOptional: "Teléfono (opcional)",
  bestWay: "Mejor forma de contactarle",
  reach_app: "Bandeja en esta app / quiosco",
  reach_helper: "A través de mi ayudante",
  reach_phone: "Teléfono",
  pickupKiosk: "¿Dónde quiere recibir sus documentos?",
  pickupKioskSub: "Sus documentos se enviarán por correo a Helping Hand y se llevarán a este quiosco. Recibirá un código de recogida.",

  docsConsent: "Permiso y firma",
  docsConsentSub: "Esto permite que un navegador de Helping Hand envíe sus solicitudes y reciba su correo. Puede cancelar en cualquier momento.",
  consentMail: "Autorizo a Helping Hand a recibir correo por mí en su dirección y a llevarlo al quiosco que elegí.",
  consentRep: "Autorizo a un navegador de Helping Hand a ayudarme a completar y enviar solicitudes a la Administración del Seguro Social, al Departamento de Salud de Florida (Estadísticas Vitales), a FLHSMV y al Departamento de Niños y Familias de Florida, y a hablar con ellos sobre mis solicitudes.",
  consentTruth: "La información que di es verdadera según mi mejor conocimiento.",
  signHere: "Firme con su dedo",
  clearSig: "Borrar",
  typedName: "Escriba su nombre completo",
  docsSubmit: "Enviar a mi navegador",
  docsSending: "Enviando…",

  docsStatusTitle: "Sus documentos",
  docsStatusIntro: "Un navegador ya está trabajando en ello. Recibirá un mensaje aquí y en cualquier quiosco cada vez que algo cambie.",
  docsCaseNumber: "Caso de documentos",
  st_collecting: "Reuniendo su información",
  st_ready: "Paquete listo — el navegador lo revisa",
  st_submitted: "Enviado al gobierno",
  st_appointment: "Cita programada — el navegador le acompañará",
  st_mailed: "Enviado por correo a Helping Hand",
  st_at_warehouse: "Llegó a Helping Hand",
  st_at_kiosk: "En el quiosco — listo para recoger",
  st_picked_up: "Recogido",
  st_issue: "Necesita atención — revise su bandeja",
  pickupCode: "Código de recogida",
  pickupAt: "Recoger en",
  appointmentAt: "Cita",
  docsAddMore: "Agregar otro documento",
  docsPhotosNote: "Agregue más fotos cuando quiera. Su navegador las ve de inmediato.",
  docsHint: "Está conectado como {name}. Toque Listo en un quiosco cuando termine.",
  docsCaseFound: "Ya tiene un caso de documentos abierto.",

  navTitle: "Mesa del navegador",
  navIntro: "Paquetes completos, listos para enviar. Abra uno para ver los formularios prellenados y actualizar cada documento a medida que avanza.",
  navOnly: "Para navegadores de Helping Hand (ayudantes, choferes y administradores).",
  navQueue: "Cola",
  navOpen: "Abrir paquete",
  navNoCases: "Todavía no hay casos de documentos.",
  navFilterAll: "Todos",
  navFilterOpen: "Necesita acción",
  navFilterKiosk: "En quiosco",
  navPacket: "Paquete",
  navPrint: "Imprimir paquete",
  navForms: "Formularios prellenados",
  navFormSs5: "Formulario SSA SS-5 — Solicitud de tarjeta del Seguro Social",
  navLink: "Navegador",
  navFilledForms: "Formularios llenados",
  navFilledFormsSub: "Los formularios oficiales, llenados con este expediente. Abra, revise, imprima y pida la firma de la persona.",
  navFormBirth: "Florida DH 726 — Solicitud de acta de nacimiento de Florida (o equivalente de otro estado)",
  navFormId: "Lista de verificación FLHSMV para ID + Certificación de domicilio / carta de verificación de personas sin hogar",
  navFormAccess: "Solicitud Florida ACCESS (SNAP, Medicaid, TCA) — envío como Community Partner",
  navMailAuth: "Autorización de correo (firmada)",
  navRepAuth: "Autorización de representante (firmada)",
  navSetStatus: "Actualizar estado",
  navKiosk: "Entregar en el quiosco",
  navCode: "Código de recogida",
  navDetail: "Nota para la persona (opcional)",
  navSave: "Guardar actualización",
  navSaved: "Actualizado. La persona ha sido notificada.",
  navNotes: "Notas del navegador",
  navFiles: "Fotos de la persona",
  navView: "Ver",
  navSigned: "Firmado",
  navNotSigned: "Sin firmar",
  navAssignMe: "Asignármelo",
  navAssigned: "Navegador",
  navUnassigned: "Sin asignar",
  navSubmittedOn: "Enviado",
  navHousehold: "Registro vinculado",
  navAppointment: "Fecha y hora de la cita",
} as const;
