import type { Dict } from "./i18n";

export const ht: Dict = {
  qHousehold: "Èske se pou ou sèl, oswa pou yon fanmi?",
  qHouseholdSomeone: "Èske se yon sèl moun, oswa yon fanmi?",
  qHouseholdHint: "Fanmi ki gen timoun gen pwòp chemen yo ak pwòp pwogram lojman yo.",
  hhSingle: "Mwen sèl",
  hhSingleSomeone: "Yon sèl moun",
  hhSingleSub: "Yon adilt",
  hhFamily: "Fanmi mwen",
  hhFamilySomeone: "Yon fanmi oswa gwoup",
  hhFamilySub: "Adilt ak timoun, yon koup, oswa fanmi ansanm",
  qFamily: "Pale nou de fanmi an",
  qFamilySomeone: "Pale nou de fanmi an",
  adults: "Adilt (18+)",
  children: "Timoun (anba 18)",
  childrenAges: "Laj timoun yo",
  childrenAgesHint: "egzanp: 3, 7, 12",
  qPregnant: "Èske gen yon moun ki ansent?",
  qSenior: "Èske gen yon moun ki gen 60 an oswa plis?",
  qRegistrant: "Ki moun k ap ranpli sa a?",
  qRegistrantHint: "Pou travayè sipò a konnen ki moun pou l rele.",
  relationship: "Mwen se",
  rel_friend: "Zanmi",
  rel_neighbor: "Vwazen",
  rel_family: "Manm fanmi",
  rel_caseworker: "Travayè sosyal",
  rel_volunteer: "Volontè",
  rel_other: "Lòt",
  qNameFamily: "Ki prenon chèf fanmi an?",
  qNameFamilySomeone: "Ki prenon chèf fanmi an?",
  qSleepFamily: "Èske fanmi an gen yon kote ki an sekirite pou dòmi aswè a?",
  qSleepFamilySomeone: "Èske fanmi an gen yon kote ki an sekirite pou dòmi aswè a?",
  qHomelessDuration: "Depi konbyen tan ou san yon kote ki estab?",
  qHomelessDurationSomeone: "Depi konbyen tan yo san yon kote ki estab?",
  hd_first: "Se premye fwa, mwens pase yon mwa",
  hd_months: "Kèk mwa",
  hd_year: "Yon ane oswa plis",
  hd_repeat: "Anpil fwa pandan ane yo",
  qDanger: "Èske gen yon moun k ap fè w mal oswa ki fè w pè kounye a?",
  qDangerSomeone: "Èske gen yon moun k ap fè yo mal oswa ki fè yo pè kounye a?",
  qDangerHint: "Ou ka sote sa. Li sèlman chanje ak ki moun nou konekte w.",
  preferNot: "Mwen pito pa di",
  dangerNow: "Ou ka jwenn lojman an sekirite apa de tout lòt bagay.",
  dangerBody: "Gratis, konfidansyèl, 24/7. Rele oswa voye START nan 88788.",
  qDocuments: "Ki papye ou genyen?",
  qDocumentsSomeone: "Ki papye yo genyen?",
  qDocumentsHint: "Pa gen papye se nòmal. N ap ede jwenn yo, epi sa chanje lòd nou fè bagay yo.",
  qSsn: "Kat Sekirite Sosyal (oswa ou konnen nimewo a)?",
  qSsnSomeone: "Kat Sekirite Sosyal (oswa yo konnen nimewo a)?",
  qBirthCert: "Batistè?",
  qBirthCertSomeone: "Batistè?",
  qIncome: "Èske gen lajan k ap antre?",
  qIncomeSomeone: "Èske gen lajan k ap antre?",
  qIncomeHint: "Sa deside ki benefis ou ka jwenn, pa si w jwenn èd.",
  inc_none: "Pa gen revni",
  inc_job: "Yon travay oswa travay pa jou",
  inc_ssi: "SSI / SSDI / Sekirite Sosyal",
  inc_other: "Yon lòt bagay",
  qSnap: "Èske w ap resevwa SNAP / EBT kounye a?",
  qSnapSomeone: "Èske yo ap resevwa SNAP / EBT kounye a?",
  qMedicaid: "Èske w gen Medicaid oswa lòt asirans sante kounye a?",
  qMedicaidSomeone: "Èske yo gen Medicaid oswa lòt asirans sante kounye a?",
  qHealth: "Kèk kesyon sou sante",
  qHealthSomeone: "Kèk kesyon sou sante",
  qHealthHint: "Sa yo louvri pòt pou lajan andikap, lojman veteran, ak tretman. Sote sa w vle.",
  qDisability: "Yon andikap oswa yon kondisyon ki bezwen swen?",
  qDisabilitySomeone: "Yon andikap oswa yon kondisyon ki bezwen swen?",
  qVeteran: "Èske w te janm sèvi nan lame ameriken?",
  qVeteranSomeone: "Èske yo te janm sèvi nan lame ameriken?",
  qRecovery: "Èske w ta renmen sipò ak alkòl oswa dwòg?",
  qRecoverySomeone: "Èske yo ta renmen sipò ak alkòl oswa dwòg?",
  qKids: "Sou timoun yo",
  qKidsSchool: "Èske timoun yo enskri lekòl?",
  qChildcare: "Èske w bezwen gadri pou yon adilt ka travay oswa ale nan randevou?",
  kidsNote: "Timoun ki san kay gen dwa legal pou rete nan lekòl yo ak transpò gratis (McKinney-Vento). Mande lekòl la pou lyezon moun san kay.",
  qNeedsHintPre: "Nou verifye sa w di nou. Ajoute oswa retire nenpòt bagay.",
  familyOf: "Fanmi {n} moun",
  need_family: "Lojman ak sipò pou fanmi",
  need_veterans: "Sèvis pou veteran",
  need_safety: "Sekirite",
  need_general: "Liy 24/7",
  partnerTitle: "Vin patnè nou",
  partnerIntro: "Gouvènman, òganizasyon san bi likratif, lopital, dantis, biznis, fondasyon, legliz: di nou sa w ka bay epi n ap mete l travay nan katye ki bezwen l lan.",
  partnerWhatWeNeed: "Sa n ap mande",
  partnerWhatWeNeedBody: "Kote pou kyòs ak finansman kyòs. Espas depo. Kamyonèt oswa machin pou transpòte manje ak rad. Chofè ak anbalè (nou anboche gradye pwogram lan). Manje, rad, kit ijyèn, telefòn. Jounen dantè ak swen medikal. Èd pou jwenn ID, kat Sekirite Sosyal, EBT, Medicaid, ak andikap. Inite lojman. Travay. Finansman.",
  orgName: "Òganizasyon",
  orgType: "Ou se",
  org_government: "Ajans gouvènman",
  org_nonprofit: "San bi likratif",
  org_hospital: "Lopital / klinik",
  org_dental: "Dantis / gwoup dantè",
  org_business: "Biznis",
  org_foundation: "Fondasyon / finansè",
  org_faith: "Legliz / gwoup relijye",
  org_individual: "Moun",
  org_other: "Lòt",
  canOffer: "Kisa w ka ofri?",
  offer_kiosk_site: "Yon kote pou kyòs",
  offer_kiosk_funding: "Finanse yon kyòs",
  offer_warehouse: "Espas depo",
  offer_vehicles: "Machin",
  offer_drivers: "Chofè / anbalè",
  offer_food: "Manje",
  offer_clothes: "Rad",
  offer_hygiene: "Kit ijyèn",
  offer_phones: "Telefòn",
  offer_dental: "Swen dantè",
  offer_medical: "Swen medikal",
  offer_mental_health: "Sante mantal / rekiperasyon",
  offer_id_documents: "Èd ak ID ak dokiman",
  offer_benefits_navigation: "Èd ak EBT / Medicaid / andikap",
  offer_housing_units: "Inite lojman",
  offer_jobs: "Travay",
  offer_funding: "Finansman",
  offer_volunteers: "Volontè",
  amountOrScale: "Kantite oswa echèl",
  amountHint: "egz. $10,000, 2 kamyonèt, 20 vizit dantè pa mwa",
  contactName: "Non kontak",
  sendOffer: "Voye òf la",
  partnerThanks: "Mèsi",
  partnerThanksBody: "Nou resevwa òf ou epi n ap kontakte w nan kèk jou.",
  individualDonate: "Ou pa yon òganizasyon? Fè don kòm moun",
  donateTitle: "Fè don",
  donateIntro: "Chak dola, sak, ak èdtan ale bay yon moun nan Miami-Dade k ap remete l sou pye.",
  giveMoney: "Bay lajan",
  giveMoneySub: "Finanse kyòs, livrezon, telefòn, ak dokiman",
  giveItems: "Bay manje, rad, oswa atik ijyèn",
  giveItemsSub: "Depoze nan yon depo; nou anbale epi livre nan 20 minit",
  giveTime: "Bay tan",
  giveTimeSub: "Vin yon moun k ap ede ki rankontre moun an pèsòn",
  donateSoon: "N ap mete don sou entènèt sou pye. Kite pwomès ou anba a epi n ap voye lyen an ba ou.",
  pledgeAmount: "Pwomès",
  sendPledge: "Voye",
  itemsWanted: "Sa nou pi bezwen: manje ki pa gate, chosèt ak sou-vètman nèf, rad gason L a 3XL, soulye, kit ijyèn, sak do, telefòn debloke.",
  whatBringing: "Kisa w ap pote?",
  dropoff: "Depo pou depoze",
  timeBody: "Moun k ap ede rankontre moun nan zòn yo, fè apèl avèk yo, akonpaye yo nan randevou, epi tcheke bwat mesaj yo. Yon èdtan pa semèn chanje yon lavi.",
  donateThanks: "Mèsi",
  donateThanksBody: "Nou resevwa l. N ap konfime ak kontak ou bay la.",
  partnersHome: "Patnè ak donatè",
  partnersHomeSub: "Bay lajan, atik, tan, oswa sèvis",
  need_benefits: "EBT / benefis manje ak kach",
  need_disability: "Andikap (SSI / SSDI)",
  need_documents: "Dokiman ak papye",
  close: "Fèmen",
  flipCamera: "Vire",
  takePhoto: "Pran foto",
  retake: "Refè",
  usePhoto: "Sèvi ak foto a",
  chooseFile: "Chwazi yon fichye",
  cameraBlocked: "Kamera a pa disponib isit la. Ou ka chwazi yon foto oswa yon fichye.",
  photoLabelShort: "Ki sa li ye? (opsyonèl)",
  rideRequest: "Ou bezwen yon woulib? Mande youn",
  rideRequested: "Woulib mande",
  rideAssigned: "Chofè fikse",
  rideEnRoute: "Chofè a sou wout",
  ridePickedUp: "Sou wout la",
  rideDone: "Woulib fini",
  rideCancelled: "Woulib anile",
  rideNoShow: "Pa te prezan",
  rideCancel: "Anile woulib",
  rides: "Woulib",
  rideFrom: "Kote pou pran ou",
  rideTo: "Ale nan",
  rideMarkAssigned: "M ap pran li",
  rideMarkEnRoute: "M sou wout",
  rideMarkPickedUp: "Pran moun nan",
  rideMarkDone: "Depoze",
  rideMarkNoShow: "Pa te prezan",
  rideDest_fl_id: "Biwo FLHSMV / Tax Collector Miami-Dade",
  rideDest_ssn_card: "Biwo Sekirite Sosyal",
  rideDest_birth_cert: "Biwo Vital Statistics",
  rideDest_benefits: "Entèvyou DCF ACCESS",
  home: "Akèy",
  benefitsShort: "Benefis",
  docsHomeShort: "ID, kat Sekirite Sosyal, batistè, EBT",
  hubTitle: "Benefis, dokiman ak swen sante",
  hubSub: "EBT, Medicaid, andikap, lojman gouvènman, batistè, ID",
  hubIntro: "Tout sa w bezwen pou w mete w sou pye, yon sèl kote. Peze yon sijè pou wè ki moun pou w rele, sa pou w di, ak sa pou w pote. Pifò nan yo ka fèt san adrès fiks.",
  hubWhatToBring: "Kòmanse isit la si w pa gen papye",
  hubWhatToBringBody: "Etap 1: jwenn yon adrès pou lèt (Sant Jounen Camillus House oswa yon ajans sipò). Etap 2: kat Sekirite Sosyal (gratis). Etap 3: batistè. Etap 4: ID Florid (frè anile si w san kay). Ak twa sa yo, ou ka aplike pou EBT, Medicaid, andikap, lojman, ak travay.",
  signInIntro: "Ou pa bezwen imel ni telefòn. Chwazi yon non ak yon PIN 6 chif. Sa se kont ou.",
  username: "Non w (yon sèl mo)",
  usernameHint: "egzanp: markis1990",
  pin: "PIN 6 chif",
  pinHint: "Chwazi 6 chif w ap sonje. Pa pataje yo.",
  useEmail: "Anplwaye: konekte ak imel",
  usePin: "Konekte ak non + PIN",
  errTaken: "Non sa a deja pran. Ajoute yon chif.",
  errUsername: "Non an dwe gen 3 a 20 lèt oswa chif, san espas.",
  errPin: "PIN lan dwe gen egzakteman 6 chif.",
  errLogin: "Non an oswa PIN lan pa kòrèk. Eseye ankò.",
  inbox: "Bwat mesaj",
  inboxIntro: "Nouvèl sou lojman, travay, sak, ak moun k ap ede vini isit la. Li yo nan app la oswa nan nenpòt kyòs.",
  inboxEmpty: "Anyen poko. Nouvèl yo ap parèt isit la.",
  new: "Nouvo",
  open: "Louvri",
  bio: "Sou ou",
  kioskInbox: "Bwat mesaj mwen",
  kioskInboxSub: "Konekte ak non w ak PIN ou pou wè nouvèl ou",
  kioskInboxWarn: "Peze Fini lè w fini pou pwochen moun nan pa wè mesaj ou yo.",
  doneSignOut: "Fini (dekonekte)",
  getUpdatesTitle: "Resevwa nouvèl san telefòn",
  getUpdatesBody: "Kreye yon kont gratis ak sèlman yon non ak yon PIN 6 chif. Nouvèl lojman, repons travay, ak mesaj moun k ap ede ap tann ou nan app la oswa nan nenpòt kyòs.",
  updatesOn: "Nouvèl yo aktive",
  updatesOnBody: "Ka sa a sove nan kont ou. Tcheke bwat mesaj ou nan nenpòt kyòs ak non w ak PIN ou.",
  appName: "Helping Hand",
  tagline: "Èd reyèl, nan lang ou, nan katye w.",
  homeQuestion: "Pou ki moun ou vin chèche èd jodi a?",
  helpingSomeone: "M ap ede yon moun",
  helpingSomeoneSub: "Jwenn bon èd pou yon moun ou rankontre",
  helpingMyself: "Mwen bezwen èd",
  helpingMyselfSub: "Lojman, manje, ID, travay, ak plis",
  jobs: "Travay",
  jobsSub: "Jwenn travay vit",
  kiosk: "Kyòs",
  kioskSub: "Pran manje ak rad",
  helpers: "Moun k ap ede",
  helpersSub: "Volontè toupre",
  account: "Kont",
  signIn: "Konekte",
  signOut: "Dekonekte",
  language: "Lang",
  next: "Kontinye",
  back: "Retounen",
  yes: "Wi",
  no: "Non",
  skip: "Sote",
  submit: "Wè plan èd mwen",
  optional: "si w vle",
  call: "Rele",
  whatToSay: "Sa pou w di lè w rele",
  hours: "Lè",

  stepOf: "Etap {a} sou {b}",
  qName: "Ki jan pou nou rele w?",
  qNameSomeone: "Ki prenon moun nan?",
  qNameHint: "Prenon oswa ti non ase.",
  qId: "Èske w gen yon ID gouvènman?",
  qIdSomeone: "Èske moun nan gen yon ID gouvènman?",
  qPhone: "Èske w gen yon telefòn?",
  qPhoneSomeone: "Èske moun nan gen yon telefòn?",
  qSleep: "Èske w gen yon kote ki an sekirite pou w dòmi aswè a?",
  qSleepSomeone: "Èske moun nan gen yon kote ki an sekirite pou l dòmi aswè a?",
  urgentTitle: "Ann fè yon travayè sipò vin jwenn ou",
  urgentBody:
    "Ou pa oblije ale nan yon abri. Miami-Dade voye travayè sipò nan zòn kote w rete a pou ede w jwenn vrè lojman (Reloje Rapid oswa Lojman Pèmanan ak Sipò). Ou pa bezwen yon adrès egzak.",
  urgentBodySomeone:
    "Li pa oblije ale nan yon abri. Miami-Dade voye travayè sipò nan zòn kote moun nan rete a pou ede l jwenn vrè lojman. Ou pa bezwen konnen egzakteman kote l dòmi.",
  qArea: "Nan ki zòn ou rete?",
  qAreaSomeone: "Nan ki zòn moun nan konn rete?",
  qAreaHint: "Yon katye, kwazman lari, oswa yon pwen repè ase.",
  qLandmark: "Kwazman lari oswa pwen repè",
  qLandmarkHint: "Egzanp: toupre Aldi sou NE 108th St",
  qHowLong: "Depi konbyen tan w ap rete la?",
  qHowLongSomeone: "Depi konbyen tan moun nan ap rete la?",
  qPay: "Èske w peye pou rete la?",
  qPaySomeone: "Èske moun nan peye pou rete la?",
  qPayDetails: "Konbyen, epi bay ki moun?",
  qNeeds: "Ak kisa w bezwen èd?",
  qNeedsSomeone: "Ak kisa moun nan bezwen èd?",
  qNeedsHint: "Chwazi tout sa ki aplike.",
  allOfAbove: "Tout sa yo",
  qContact: "Ki jan yon moun k ap ede ka jwenn ou?",
  qContactSomeone: "Ki jan yon moun k ap ede ka jwenn ou (ou menm k ap ede a)?",
  qContactHint: "Telefòn oswa imel. Si pa gen telefòn, di nou kilè ak ki kote yo ka jwenn ou.",
  qNotes: "Gen lòt bagay nou ta dwe konnen?",
  saving: "Ap anrejistre...",

  need_housing: "Lojman",
  need_id: "ID",
  need_ssn: "Kat Sekirite Sosyal",
  need_food: "Manje",
  need_clothes: "Rad",
  need_job: "Yon travay",
  need_healthcare: "Swen sante",
  need_addiction: "Sipò pou depandans",
  need_phone: "Yon telefòn",

  dur_days: "Kèk jou",
  dur_weeks: "Kèk semèn",
  dur_months: "Kèk mwa",
  dur_year: "Yon ane oswa plis",

  planTitle: "Plan èd ou",
  planTitleSomeone: "Plan èd pou {name}",
  planIntro: "Men ki moun pou w rele pou chak bezwen, ak sa pou w di. Yon moun k ap ede ka pase sou sa avè w an pèsòn tou.",
  yourNumber: "Nimewo ka w",
  showThis: "Montre sa nan nenpòt kyòs oswa bay nenpòt moun k ap ede.",
  findHelper: "Konekte m ak yon moun k ap ede toupre",
  findHelperSub: "Yon moun nan zòn ou ki ka rankontre w an pèsòn epi ede w ak apèl, papye, ak transpò.",
  requestOutreach: "Mande yon travayè sipò nan lari",
  outreachRequested: "Demann lan anrejistre. Rele liy èd la pou asire yo louvri l jodi a.",
  foodClothesNow: "Ou bezwen manje oswa rad kounye a?",
  foodClothesNowSub: "Mande yon sak nan kyòs ki pi pre a. Nou prepare l nan depo a epi li rive nan anviwon 20 minit.",
  requestPickup: "Mande yon sak",
  seeJobs: "Wè travay ki disponib",
  noResources: "N ap toujou ajoute resous pou bezwen sa a. Rele 211 pou kounye a.",
  startOver: "Rekòmanse",

  helpersTitle: "Moun k ap ede toupre w",
  helpersIntro: "Moun sa yo ofri pou rankontre an pèsòn nan zòn ou.",
  requestMatch: "Mande pou rankontre",
  matchSent: "Demann lan voye. Y ap kontakte w ak kontak ou bay la.",
  noHelpers: "Poko gen moun k ap ede nan zòn sa a. Nou sove demann ou epi n ap konekte w le pli vit posib.",
  becomeHelper: "Vin yon moun k ap ede",
  helperDash: "Tablo moun k ap ede",
  openRequests: "Demann ki louvri nan zòn ou",
  allAreas: "Tout zòn",
  accept: "Mwen ka ede ak sa",
  accepted: "Nou konekte w. Kontakte moun nan ak kontak ki anba a.",
  noOpen: "Pa gen demann louvri kounye a. Mèsi paske w la.",

  jobsTitle: "Travay k ap anboche kounye a",
  jobsIntro: "Anplwayè isit la konnen ou ka poko gen ID, adrès, oswa telefòn. Chèche etikèt vèt yo.",
  postJob: "Pibliye yon travay",
  apply: "Aplike",
  applyTitle: "Aplike pou {title}",
  yourName: "Non w",
  yourContact: "Telefòn, imel, oswa kote pou jwenn ou",
  message: "Mesaj (si w vle)",
  sendApplication: "Voye aplikasyon",
  applicationSent: "Voye. Anplwayè a ap kontakte w.",
  jobsSearch: "Chèche: lave asyèt, konstriksyon, netwayaj…",
  jobsAll: "Tout travay",
  jobsThisWeek: "Anboche semèn sa a",
  jobsNone: "Pa gen travay ki koresponn. Eseye yon lòt mo oswa retire filtè yo.",
  tag_thisWeek: "Anboche semèn sa a",
  tag_noExp: "Pa bezwen eksperyans ni diplòm",
  cat_kitchen: "Restoran ak kwizin",
  cat_construction: "Konstriksyon",
  cat_cleaning: "Netwayaj",
  cat_cafeteria: "Kafeterya ak sèvis manje",
  cat_warehouse: "Depo ak demenajman",
  cat_landscaping: "Jaden ak teren",
  cat_hotel: "Otèl ak netwayaj chanm",
  tag_noId: "Pa bezwen ID",
  tag_noAddress: "Pa bezwen adrès",
  tag_sameDay: "Peye menm jou",
  jobTitle: "Tit travay",
  company: "Konpayi",
  pay: "Salè",
  jobType: "Kalite",
  description: "Deskripsyon",
  requirements: "Kondisyon",
  contactPhone: "Telefòn kontak",
  contactEmail: "Imel kontak",
  howToApply: "Ki jan pou aplike",
  publish: "Pibliye",
  type_full_time: "Tan plen",
  type_part_time: "Tan pasyèl",
  type_day_labor: "Travay pa jou",
  type_gig: "Ti djòb",
  type_temp: "Tanporè",
  noJobs: "Poko gen travay pibliye.",
  signInToPost: "Konekte kòm anplwayè pou pibliye yon travay.",

  kioskTitle: "Byenveni",
  kioskQuestion: "Ou bezwen manje oswa rad?",
  kioskYes: "Wi, mwen bezwen manje oswa rad",
  kioskHelp: "Mwen bezwen lòt èd",
  kioskStatus: "Tcheke sak mwen",
  kioskFood: "Manje",
  kioskClothes: "Rad",
  kioskHygiene: "Kit ijyèn",
  sizeTop: "Gwosè chemiz",
  sizeBottom: "Gwosè pantalon",
  sizeShoes: "Gwosè soulye",
  kioskCode: "Kòd ou pou pran sak la",
  kioskArriving: "Y ap prepare l nan depo a. L ap rive nan kyòs sa a nan anviwon {n} minit.",
  kioskShowCode: "Montre kòd sa a lè sak la rive.",
  enterCode: "Antre kòd ou",
  check: "Tcheke",
  status_requested: "Resevwa",
  status_packing: "Y ap prepare",
  status_en_route: "Sou wout",
  status_delivered: "Nan kyòs la",
  status_picked_up: "Pran",
  status_cancelled: "Anile",
  notFound: "Kòd la pa jwenn.",
  kioskPlace: "Mande",

  email: "Imel",
  password: "Modpas",
  displayName: "Non",
  role: "Mwen se",
  role_seeker: "Yon moun k ap chèche èd",
  role_helper: "Yon moun k ap ede / volontè",
  role_employer: "Yon anplwayè",
  role_driver: "Yon chofè / anbalè",
  createAccount: "Kreye kont",
  haveAccount: "Ou gen kont deja? Konekte",
  needAccount: "Nouvo isit la? Kreye yon kont",
  checkEmail: "Tcheke imel ou pou konfime kont ou, epi konekte.",
  myArea: "Zòn mwen",
  canMeet: "Mwen ka rankontre moun an pèsòn",
  helperSkills: "Mwen ka ede ak",
  save: "Sove",
  saved: "Sove.",
  profile: "Pwofil",
  driverDash: "Tablo chofè",
  deliveries: "Livrezon",
  markPacking: "Kòmanse prepare",
  markEnRoute: "Sou wout",
  markDelivered: "Livre nan kyòs",
  markPickedUp: "Pran",
  minutesAgo: "{n} min pase",
  emergency: "Si yon moun an danje kounye a, rele 911.",
  // --- Ajoute nan revizyon konsepsyon an. NOUVO TÈKS — bezwen revizyon. ---
  menu: "Meni",
  loading: "Ap chaje…",
  retry: "Eseye ankò",
  errGeneric: "Gen yon pwoblèm. Anyen pa pèdi — tanpri eseye ankò.",
  errHelp: "Si li kontinye rive, rele 211. Li gratis, 24 sou 24, nan lang ou.",
  privacyNote: "Nou pataje sèlman sa ou mande nou pataje. Ou ka rete lè ou vle.",
  areaLabel: "Zòn",
};
