// Document Center strings (Haitian Creole)
export const docsHt = {
  docsTitle: "Sant Dokiman",
  docsHome: "Jwenn dokiman mwen yo",
  docsHomeSub: "ID, kat Sekirite Sosyal, batistè, EBT ak Medicaid — pa gen apèl telefòn, pa gen papye pou ranpli",
  docsIntro:
    "Reponn yon sèl fwa. Nou ranpli fòm gouvènman yo pou ou, yon navigatè Helping Hand voye yo, epi dokiman ou yo rive nan yon kyòs toupre w. Ou pa janm bezwen rele pèsonn.",
  docsSignIn: "Konekte oswa kreye yon kont pou nou ka kenbe dokiman ou yo an sekirite epi di w lè yo rive.",
  docsPlanCard: "Nou ka kòmanse kounye a menm ak ID ou, kat Sekirite Sosyal, batistè ak benefis ou yo.",
  docsStart: "Kòmanse dokiman mwen yo",
  docsMine: "Dokiman mwen yo",

  docsWhich: "Kisa ou bezwen?",
  docsWhichSub: "Chwazi tout sa ki aplike. Nou okipe lòd yo dwe ale a.",
  doc_ssn_card: "Kat Sekirite Sosyal",
  doc_ssn_card_sub: "Kat ranplasman. Gratis. Nesesè pou travay ak benefis.",
  doc_birth_cert: "Batistè",
  doc_birth_cert_sub: "Yon kopi sètifye ki soti nan eta kote ou fèt la. Nesesè pou jwenn yon ID.",
  doc_fl_id: "Kat ID Florid",
  doc_fl_id_sub: "ID eta a. Gratis ak yon lèt verifikasyon sanzabri. Yon ti vizit an pèsòn — yon navigatè ale avè w.",
  doc_benefits: "EBT, Medicaid ak èd lajan kach",
  doc_benefits_sub: "Manje (SNAP), kouvèti sante ak èd lajan atravè Florida ACCESS.",

  docsAbout: "Sou ou menm",
  docsAboutSub: "Sèvi ak non ki sou batistè w la, menm si ou itilize yon lòt non.",
  legalFirst: "Prenon",
  legalMiddle: "Dezyèm prenon",
  legalLast: "Siyati",
  otherNames: "Lòt non ou te itilize",
  dob: "Dat nesans",
  sex: "Sèks sou batistè w la",
  sex_male: "Gason",
  sex_female: "Fi",
  sex_x: "X / lòt",
  birthPlace: "Ki kote ou fèt?",
  birthCity: "Vil",
  birthState: "Eta",
  birthCountry: "Peyi",

  docsParents: "Paran ou yo",
  docsParentsSub: "Sekirite Sosyal ak biwo batistè a sèvi ak sa pou jwenn dosye w. Ou ka kite l vid si ou pa konnen.",
  motherName: "Non konplè manman w",
  motherMaiden: "Non jenn fi manman w (non anvan maryaj)",
  fatherName: "Non konplè papa w",

  docsSsn: "Sekirite Sosyal ak sitwayènte",
  ssnKnown: "Èske ou konnen nimewo Sekirite Sosyal ou?",
  ssnLast4: "4 dènye chif yo (sèlman si ou konnen yo)",
  ssnFullLater: "W ap bay navigatè w la nimewo konplè a an pèsòn. Pa janm tape l nan yon kyòs.",
  usCitizen: "Èske ou se yon sitwayen ameriken?",
  notCitizenNote: "Pa gen pwoblèm. N ap ede w ak dokiman ou ka jwenn yo epi konekte w ak èd legal imigrasyon.",

  docsHave: "Kisa ou genyen kounye a?",
  docsHaveSub: "Nenpòt papye ak non ou ede. Pran yon foto nenpòt sa ou genyen — li rete prive epi se sèlman navigatè w la ki ka wè l.",
  havePhotoId: "Nenpòt ID ak foto (menm si li ekspire)",
  haveBirthCert: "Batistè",
  haveSsnCard: "Kat Sekirite Sosyal",
  haveOther: "Nenpòt lòt bagay (dosye lekòl, kat medikal, lèt ak non ou, souch chèk…)",
  addPhoto: "Ajoute yon foto",
  photoLabel: "Kisa sa ye?",
  uploading: "Ap voye…",
  photoAdded: "Foto sove.",
  photos: "Foto yo",

  docsReach: "Kijan nou ka kontakte w?",
  docsReachSub: "Chak mizajou ale nan bwat mesaj ou nan app sa a ak nan nenpòt kyòs. Si ou gen telefòn, ou ka ajoute l tou.",
  phoneOptional: "Telefòn (opsyonèl)",
  bestWay: "Pi bon fason pou kontakte w",
  reach_app: "Bwat mesaj nan app sa a / kyòs",
  reach_helper: "Atravè moun k ap ede m nan",
  reach_phone: "Telefòn",
  pickupKiosk: "Ki kote ou vle resevwa dokiman ou yo?",
  pickupKioskSub: "Dokiman ou yo ap poste bay Helping Hand epi pote nan kyòs sa a. W ap resevwa yon kòd pou pran yo.",

  docsConsent: "Pèmisyon ak siyati",
  docsConsentSub: "Sa pèmèt yon navigatè Helping Hand voye aplikasyon ou yo epi resevwa lèt ou yo. Ou ka anile nenpòt lè.",
  consentMail: "Mwen otorize Helping Hand resevwa lèt pou mwen nan adrès li epi pote yo nan kyòs mwen chwazi a.",
  consentRep: "Mwen otorize yon navigatè Helping Hand ede m ranpli epi voye aplikasyon bay Administrasyon Sekirite Sosyal, Depatman Sante Florid (Estatistik Vital), FLHSMV ak Depatman Timoun ak Fanmi Florid, epi pale avèk yo sou aplikasyon mwen yo.",
  consentTruth: "Enfòmasyon mwen bay yo vre dapre sa mwen konnen.",
  signHere: "Siyen ak dwèt ou",
  clearSig: "Efase",
  typedName: "Tape non konplè w",
  docsSubmit: "Voye bay navigatè mwen",
  docsSending: "Ap voye…",

  docsStatusTitle: "Dokiman ou yo",
  docsStatusIntro: "Yon navigatè ap travay sou li. W ap resevwa yon mesaj isit la ak nan nenpòt kyòs chak fwa yon bagay chanje.",
  docsCaseNumber: "Dosye dokiman",
  st_collecting: "N ap rasanble enfòmasyon ou",
  st_ready: "Pakè pare — navigatè a ap revize",
  st_submitted: "Voye bay gouvènman an",
  st_appointment: "Randevou fikse — navigatè a ap ale avè w",
  st_mailed: "Poste bay Helping Hand",
  st_at_warehouse: "Rive nan Helping Hand",
  st_at_kiosk: "Nan kyòs la — pare pou pran",
  st_picked_up: "Pran",
  st_issue: "Bezwen atansyon — tcheke bwat mesaj ou",
  pickupCode: "Kòd pou pran",
  pickupAt: "Pran nan",
  appointmentAt: "Randevou",
  docsAddMore: "Ajoute yon lòt dokiman",
  docsPhotosNote: "Ajoute plis foto nenpòt lè. Navigatè w la wè yo touswit.",
  docsHint: "Ou konekte kòm {name}. Peze Fini nan yon kyòs lè ou fini.",
  docsCaseFound: "Ou deja gen yon dosye dokiman ouvè.",

  navTitle: "Biwo navigatè",
  navIntro: "Pakè konplè, pare pou voye. Ouvri youn pou wè fòm yo deja ranpli epi mete chak dokiman ajou pandan l ap avanse.",
  navOnly: "Pou navigatè Helping Hand (moun k ap ede, chofè ak administratè).",
  navQueue: "Lis datant",
  navOpen: "Ouvri pakè",
  navNoCases: "Poko gen dosye dokiman.",
  navFilterAll: "Tout",
  navFilterOpen: "Bezwen aksyon",
  navFilterKiosk: "Nan kyòs",
  navPacket: "Pakè",
  navPrint: "Enprime pakè",
  navForms: "Fòm deja ranpli",
  navFormSs5: "Fòm SSA SS-5 — Aplikasyon pou kat Sekirite Sosyal",
  navLink: "Navigatè",
  navFilledForms: "Fòm ranpli",
  navFilledFormsSub: "Fòm ofisyèl yo, ranpli ak dosye sa a. Ouvri, tcheke, enprime, epi fè moun nan siyen.",
  navFormBirth: "Florida DH 726 — Aplikasyon pou batistè Florid (oswa ekivalan lòt eta)",
  navFormId: "Lis verifikasyon ID FLHSMV + Sètifikasyon adrès / lèt verifikasyon sanzabri",
  navFormAccess: "Aplikasyon Florida ACCESS (SNAP, Medicaid, TCA) — soumisyon Community Partner",
  navMailAuth: "Otorizasyon lèt (siyen)",
  navRepAuth: "Otorizasyon reprezantan (siyen)",
  navSetStatus: "Mete estati ajou",
  navKiosk: "Livre nan kyòs",
  navCode: "Kòd pou pran",
  navDetail: "Nòt pou moun nan (opsyonèl)",
  navSave: "Sove mizajou",
  navSaved: "Mete ajou. Moun nan resevwa yon notifikasyon.",
  navNotes: "Nòt navigatè",
  navFiles: "Foto moun nan voye",
  navView: "Gade",
  navSigned: "Siyen",
  navNotSigned: "Pa siyen",
  navAssignMe: "Bay mwen li",
  navAssigned: "Navigatè",
  navUnassigned: "Pa asiyen",
  navSubmittedOn: "Voye",
  navHousehold: "Dosye lye",
  navAppointment: "Dat ak lè randevou",
} as const;
