// Document Center strings (English)
export const docsEn = {
  docsTitle: "Document Center",
  docsHome: "Get my documents",
  docsHomeSub: "ID, Social Security card, birth certificate, EBT & Medicaid — no phone calls, no paperwork",
  docsIntro:
    "Answer once. We fill out the government forms for you, a Helping Hand navigator sends them in, and your documents come back to a kiosk near you. You never have to call anyone.",
  docsSignIn: "Sign in or make an account so we can keep your documents safe and tell you when they arrive.",
  docsPlanCard: "We can get your ID, Social Security card, birth certificate and benefits started right now.",
  docsStart: "Start my documents",
  docsMine: "My documents",

  // step 1: which documents
  docsWhich: "What do you need?",
  docsWhichSub: "Pick everything that applies. We handle the order they need to go in.",
  doc_ssn_card: "Social Security card",
  doc_ssn_card_sub: "Replacement card. Free. Needed for work and benefits.",
  doc_birth_cert: "Birth certificate",
  doc_birth_cert_sub: "A certified copy from the state where you were born. Needed to get an ID.",
  doc_fl_id: "Florida ID card",
  doc_fl_id_sub: "State ID. Free with a homeless-verification letter. One short in-person visit — a navigator goes with you.",
  doc_benefits: "EBT, Medicaid & cash assistance",
  doc_benefits_sub: "Food (SNAP), health coverage and cash help through Florida ACCESS.",

  // step 2: about you
  docsAbout: "About you",
  docsAboutSub: "Use the name on your birth certificate, even if you go by something else.",
  legalFirst: "First name",
  legalMiddle: "Middle name",
  legalLast: "Last name",
  otherNames: "Other names you have used",
  dob: "Date of birth",
  sex: "Sex on your birth certificate",
  sex_male: "Male",
  sex_female: "Female",
  sex_x: "X / other",
  birthPlace: "Where were you born?",
  birthCity: "City",
  birthState: "State",
  birthCountry: "Country",

  // step 3: parents
  docsParents: "Your parents",
  docsParentsSub: "Social Security and the birth-certificate office use this to find your record. It is okay to leave blank if you do not know.",
  motherName: "Mother's full name",
  motherMaiden: "Mother's maiden name (name before marriage)",
  fatherName: "Father's full name",

  // step 4: ssn & citizenship
  docsSsn: "Social Security & citizenship",
  ssnKnown: "Do you know your Social Security number?",
  ssnLast4: "Last 4 digits (only if you know them)",
  ssnFullLater: "You will give the full number to your navigator in person. Never type it into a kiosk.",
  usCitizen: "Are you a U.S. citizen?",
  notCitizenNote: "That is okay. We will help with the documents you can get and connect you with immigration legal aid.",

  // step 5: what you have
  docsHave: "What do you have right now?",
  docsHaveSub: "Any paper with your name helps. Take a photo of anything you have — it stays private and only your navigator can see it.",
  havePhotoId: "Any photo ID (even expired)",
  haveBirthCert: "Birth certificate",
  haveSsnCard: "Social Security card",
  haveOther: "Anything else (school record, medical card, mail with your name, pay stub…)",
  addPhoto: "Add a photo",
  photoLabel: "What is this?",
  uploading: "Uploading…",
  photoAdded: "Photo saved.",
  photos: "Photos",

  // step 6: reach & pickup
  docsReach: "How do we reach you?",
  docsReachSub: "Every update goes to your inbox in this app and at any kiosk. If you have a phone, you can add it too.",
  phoneOptional: "Phone (optional)",
  bestWay: "Best way to reach you",
  reach_app: "Inbox in this app / kiosk",
  reach_helper: "Through my helper",
  reach_phone: "Phone",
  pickupKiosk: "Where should your documents be delivered?",
  pickupKioskSub: "Your documents will be mailed to Helping Hand and brought to this kiosk. You will get a pickup code.",

  // step 7: consent
  docsConsent: "Permission & signature",
  docsConsentSub: "This lets a Helping Hand navigator send your applications and receive your mail. You can cancel any time.",
  consentMail: "I authorize Helping Hand to receive mail for me at its address and to bring it to the kiosk I chose.",
  consentRep: "I authorize a Helping Hand navigator to help me complete and submit applications to the Social Security Administration, the Florida Department of Health (Vital Statistics), FLHSMV and the Florida Department of Children and Families, and to speak with them about my applications.",
  consentTruth: "The information I gave is true to the best of my knowledge.",
  signHere: "Sign with your finger",
  clearSig: "Clear",
  typedName: "Type your full name",
  docsSubmit: "Send to my navigator",
  docsSending: "Sending…",

  // status
  docsStatusTitle: "Your documents",
  docsStatusIntro: "A navigator is on it. You will get a message here and at any kiosk every time something changes.",
  docsCaseNumber: "Document case",
  st_collecting: "Getting your information",
  st_ready: "Packet ready — navigator reviewing",
  st_submitted: "Sent to the government",
  st_appointment: "Appointment set — navigator will go with you",
  st_mailed: "Mailed to Helping Hand",
  st_at_warehouse: "Arrived at Helping Hand",
  st_at_kiosk: "At the kiosk — ready to pick up",
  st_picked_up: "Picked up",
  st_issue: "Needs attention — check your inbox",
  pickupCode: "Pickup code",
  pickupAt: "Pick up at",
  appointmentAt: "Appointment",
  docsAddMore: "Add another document",
  docsPhotosNote: "Add more photos any time. Your navigator sees them right away.",
  docsHint: "You are signed in as {name}. Tap Done at a kiosk when you finish.",
  docsCaseFound: "You already have a document case open.",

  // navigator
  navTitle: "Navigator desk",
  navIntro: "Complete packets, ready to send. Open one to see the pre-filled forms and update each document as it moves.",
  navOnly: "For Helping Hand navigators (helpers, drivers and admins).",
  navQueue: "Queue",
  navOpen: "Open packet",
  navNoCases: "No document cases yet.",
  navFilterAll: "All",
  navFilterOpen: "Needs action",
  navFilterKiosk: "At kiosk",
  navPacket: "Packet",
  navPrint: "Print packet",
  navForms: "Pre-filled forms",
  navFormSs5: "SSA form SS-5 — Application for a Social Security card",
  navLink: "Navigator",
  navFilledForms: "Filled forms",
  navFilledFormsSub: "The official forms, filled in from this packet. Open, check, print, and have the person sign.",
  navFormBirth: "Florida DH 726 — Application for Florida birth record (or out-of-state equivalent)",
  navFormId: "FLHSMV ID checklist + Certification of Address / homeless-verification letter",
  navFormAccess: "Florida ACCESS application (SNAP, Medicaid, TCA) — Community Partner submission",
  navMailAuth: "Mail authorization (signed)",
  navRepAuth: "Representative authorization (signed)",
  navSetStatus: "Update status",
  navKiosk: "Deliver to kiosk",
  navCode: "Pickup code",
  navDetail: "Note to the person (optional)",
  navSave: "Save update",
  navSaved: "Updated. The person has been notified.",
  navNotes: "Navigator notes",
  navFiles: "Photos from the person",
  navView: "View",
  navSigned: "Signed",
  navNotSigned: "Not signed",
  navAssignMe: "Assign to me",
  navAssigned: "Navigator",
  navUnassigned: "Unassigned",
  navSubmittedOn: "Submitted",
  navHousehold: "Linked intake",
  navAppointment: "Appointment date & time",
} as const;
