import type { Dict } from "./i18n";

export const es: Dict = {
  qHousehold: "¿Es para usted solo, o para una familia?",
  qHouseholdSomeone: "¿Es una persona, o una familia?",
  qHouseholdHint: "Las familias con niños tienen su propia vía y sus propios programas de vivienda.",
  hhSingle: "Solo yo",
  hhSingleSomeone: "Una persona",
  hhSingleSub: "Un adulto",
  hhFamily: "Mi familia",
  hhFamilySomeone: "Una familia o grupo",
  hhFamilySub: "Adultos con niños, una pareja o parientes juntos",
  qFamily: "Cuéntenos sobre la familia",
  qFamilySomeone: "Cuéntenos sobre la familia",
  adults: "Adultos (18+)",
  children: "Niños (menores de 18)",
  childrenAges: "Edades de los niños",
  childrenAgesHint: "ejemplo: 3, 7, 12",
  qPregnant: "¿Alguien está embarazada?",
  qSenior: "¿Alguien tiene 60 años o más?",
  qRegistrant: "¿Quién está llenando esto?",
  qRegistrantHint: "Para que el trabajador de alcance sepa a quién llamar.",
  relationship: "Soy su",
  rel_friend: "Amigo/a",
  rel_neighbor: "Vecino/a",
  rel_family: "Familiar",
  rel_caseworker: "Trabajador/a social",
  rel_volunteer: "Voluntario/a",
  rel_other: "Otro",
  qNameFamily: "¿Cuál es el nombre del jefe de familia?",
  qNameFamilySomeone: "¿Cuál es el nombre del jefe de familia?",
  qSleepFamily: "¿La familia tiene un lugar seguro para dormir esta noche?",
  qSleepFamilySomeone: "¿La familia tiene un lugar seguro para dormir esta noche?",
  qHomelessDuration: "¿Cuánto tiempo lleva sin un lugar estable?",
  qHomelessDurationSomeone: "¿Cuánto tiempo lleva la persona sin un lugar estable?",
  hd_first: "Es la primera vez, menos de un mes",
  hd_months: "Unos meses",
  hd_year: "Un año o más",
  hd_repeat: "Muchas veces a lo largo de los años",
  qDanger: "¿Alguien le está haciendo daño o le da miedo ahora mismo?",
  qDangerSomeone: "¿Alguien le está haciendo daño a la persona o le da miedo ahora mismo?",
  qDangerHint: "Puede omitirlo. Solo cambia con quién le conectamos.",
  preferNot: "Prefiero no decir",
  dangerNow: "Puede conseguir vivienda segura separada de todo lo demás.",
  dangerBody: "Gratis, confidencial, 24/7. Llame o envíe START al 88788.",
  qDocuments: "¿Qué documentos tiene?",
  qDocumentsSomeone: "¿Qué documentos tiene la persona?",
  qDocumentsHint: "No tener papeles es normal. Ayudaremos a conseguirlos, y cambia el orden en que hacemos las cosas.",
  qSsn: "¿Tarjeta del Seguro Social (o sabe el número)?",
  qSsnSomeone: "¿Tarjeta del Seguro Social (o sabe el número)?",
  qBirthCert: "¿Acta de nacimiento?",
  qBirthCertSomeone: "¿Acta de nacimiento?",
  qIncome: "¿Entra algo de dinero?",
  qIncomeSomeone: "¿Entra algo de dinero?",
  qIncomeHint: "Esto decide qué beneficios puede recibir, no si recibe ayuda.",
  inc_none: "Sin ingresos",
  inc_job: "Un trabajo o jornal",
  inc_ssi: "SSI / SSDI / Seguro Social",
  inc_other: "Otra cosa",
  qSnap: "¿Recibe SNAP / EBT ahora?",
  qSnapSomeone: "¿Recibe SNAP / EBT ahora?",
  qMedicaid: "¿Tiene Medicaid u otro seguro médico ahora?",
  qMedicaidSomeone: "¿Tiene Medicaid u otro seguro médico ahora?",
  qHealth: "Unas preguntas de salud",
  qHealthSomeone: "Unas preguntas de salud",
  qHealthHint: "Abren puertas a dinero por discapacidad, vivienda para veteranos y tratamiento. Omita lo que quiera.",
  qDisability: "¿Una discapacidad o condición continua que necesita atención?",
  qDisabilitySomeone: "¿Una discapacidad o condición continua que necesita atención?",
  qVeteran: "¿Sirvió en el ejército de EE. UU.?",
  qVeteranSomeone: "¿Sirvió en el ejército de EE. UU.?",
  qRecovery: "¿Le gustaría apoyo con alcohol o drogas?",
  qRecoverySomeone: "¿Le gustaría a la persona apoyo con alcohol o drogas?",
  qKids: "Sobre los niños",
  qKidsSchool: "¿Los niños están inscritos en la escuela?",
  qChildcare: "¿Se necesita cuidado infantil para que un adulto pueda trabajar o ir a citas?",
  kidsNote: "Los niños sin hogar tienen derecho legal a seguir en su escuela con transporte gratis (McKinney-Vento). Pida el enlace para personas sin hogar en la escuela.",
  qNeedsHintPre: "Revisamos lo que nos dijo. Agregue o quite lo que quiera.",
  familyOf: "Familia de {n}",
  need_family: "Vivienda y apoyo familiar",
  need_veterans: "Servicios para veteranos",
  need_safety: "Seguridad",
  need_general: "Líneas 24/7",
  partnerTitle: "Sea nuestro aliado",
  partnerIntro: "Gobierno, organizaciones sin fines de lucro, hospitales, dentistas, empresas, fundaciones, iglesias: díganos qué puede dar y lo pondremos a trabajar en el barrio que lo necesita.",
  partnerWhatWeNeed: "Lo que pedimos",
  partnerWhatWeNeedBody: "Ubicaciones y financiamiento para kioscos. Espacio de almacén. Camionetas o autos para mover comida y ropa. Conductores y empacadores (contratamos a graduados del programa). Comida, ropa, kits de higiene, teléfonos. Jornadas dentales y atención médica. Ayuda para obtener identificación, tarjeta del Seguro Social, EBT, Medicaid y discapacidad. Unidades de vivienda. Empleos. Fondos.",
  orgName: "Organización",
  orgType: "Usted es",
  org_government: "Agencia de gobierno",
  org_nonprofit: "Sin fines de lucro",
  org_hospital: "Hospital / clínica",
  org_dental: "Dentista / grupo dental",
  org_business: "Empresa",
  org_foundation: "Fundación / financiador",
  org_faith: "Iglesia / grupo religioso",
  org_individual: "Persona",
  org_other: "Otro",
  canOffer: "¿Qué puede ofrecer?",
  offer_kiosk_site: "Un lugar para un kiosco",
  offer_kiosk_funding: "Financiar un kiosco",
  offer_warehouse: "Espacio de almacén",
  offer_vehicles: "Vehículos",
  offer_drivers: "Conductores / empacadores",
  offer_food: "Comida",
  offer_clothes: "Ropa",
  offer_hygiene: "Kits de higiene",
  offer_phones: "Teléfonos",
  offer_dental: "Atención dental",
  offer_medical: "Atención médica",
  offer_mental_health: "Salud mental / recuperación",
  offer_id_documents: "Ayuda con identificación y documentos",
  offer_benefits_navigation: "Ayuda con EBT / Medicaid / discapacidad",
  offer_housing_units: "Unidades de vivienda",
  offer_jobs: "Empleos",
  offer_funding: "Fondos",
  offer_volunteers: "Voluntarios",
  amountOrScale: "Cantidad o escala",
  amountHint: "ej. $10,000, 2 camionetas, 20 citas dentales al mes",
  contactName: "Nombre de contacto",
  sendOffer: "Enviar oferta",
  partnerThanks: "Gracias",
  partnerThanksBody: "Recibimos su oferta y le contactaremos en unos días.",
  individualDonate: "¿No es una organización? Done como persona",
  donateTitle: "Donar",
  donateIntro: "Cada dólar, bolsa y hora va a alguien en Miami-Dade que está saliendo adelante.",
  giveMoney: "Dar dinero",
  giveMoneySub: "Financia kioscos, entregas, teléfonos y documentos",
  giveItems: "Dar comida, ropa o artículos de higiene",
  giveItemsSub: "Entregue en un almacén; empacamos y entregamos en 20 minutos",
  giveTime: "Dar tiempo",
  giveTimeSub: "Sea un ayudante que se reúne con personas",
  donateSoon: "Las donaciones en línea se están configurando. Deje su promesa abajo y le enviaremos el enlace.",
  pledgeAmount: "Promesa",
  sendPledge: "Enviar",
  itemsWanted: "Más necesitado: comida no perecedera, calcetines y ropa interior nuevos, ropa de hombre L a 3XL, zapatos, kits de higiene, mochilas, teléfonos desbloqueados.",
  whatBringing: "¿Qué va a traer?",
  dropoff: "Almacén de entrega",
  timeBody: "Los ayudantes se reúnen con personas en su zona, hacen llamadas con ellas, las acompañan a citas y revisan su bandeja. Una hora a la semana cambia una vida.",
  donateThanks: "Gracias",
  donateThanksBody: "Lo recibimos. Confirmaremos por el contacto que dio.",
  partnersHome: "Aliados y donantes",
  partnersHomeSub: "Dé dinero, artículos, tiempo o servicios",
  need_benefits: "EBT / beneficios de comida y efectivo",
  need_disability: "Discapacidad (SSI / SSDI)",
  need_documents: "Documentos y papeles",
  close: "Cerrar",
  flipCamera: "Voltear",
  takePhoto: "Tomar foto",
  retake: "Repetir",
  usePhoto: "Usar foto",
  chooseFile: "Elegir un archivo",
  cameraBlocked: "La cámara no está disponible aquí. Puede elegir una foto o un archivo.",
  photoLabelShort: "¿Qué es? (opcional)",
  rideRequest: "¿Necesita transporte? Pídalo aquí",
  rideRequested: "Viaje solicitado",
  rideAssigned: "Conductor asignado",
  rideEnRoute: "El conductor va en camino",
  ridePickedUp: "En camino",
  rideDone: "Viaje completado",
  rideCancelled: "Viaje cancelado",
  rideNoShow: "No se presentó",
  rideCancel: "Cancelar viaje",
  rides: "Viajes",
  rideFrom: "Recogida",
  rideTo: "Destino",
  rideMarkAssigned: "Yo lo llevo",
  rideMarkEnRoute: "Voy en camino",
  rideMarkPickedUp: "Recogido",
  rideMarkDone: "Entregado",
  rideMarkNoShow: "No se presentó",
  rideDest_fl_id: "Oficina FLHSMV / Tax Collector de Miami-Dade",
  rideDest_ssn_card: "Oficina del Seguro Social",
  rideDest_birth_cert: "Oficina de Vital Statistics",
  rideDest_benefits: "Entrevista de DCF ACCESS",
  home: "Inicio",
  benefitsShort: "Beneficios",
  docsHomeShort: "ID, Seguro Social, acta de nacimiento, EBT",
  hubTitle: "Beneficios, documentos y salud",
  hubSub: "EBT, Medicaid, discapacidad, vivienda pública, acta de nacimiento, identificación",
  hubIntro: "Todo lo que necesita para establecerse, en un solo lugar. Toque un tema para ver a quién llamar, qué decir y qué llevar. La mayoría se puede hacer sin dirección fija.",
  hubWhatToBring: "Empiece aquí si no tiene papeles",
  hubWhatToBringBody: "Paso 1: consiga una dirección para correo (Centro de Día Camillus House o una agencia de alcance). Paso 2: tarjeta del Seguro Social (gratis). Paso 3: acta de nacimiento. Paso 4: identificación de Florida (sin costo si no tiene hogar). Con esos tres puede solicitar EBT, Medicaid, discapacidad, vivienda y empleo.",
  signInIntro: "No necesita correo ni teléfono. Elija un nombre y un PIN de 6 dígitos. Esa es su cuenta.",
  username: "Su nombre (una palabra)",
  usernameHint: "ejemplo: marcos1990",
  pin: "PIN de 6 dígitos",
  pinHint: "Elija 6 números que recuerde. No los comparta.",
  useEmail: "Personal: iniciar sesión con correo",
  usePin: "Iniciar sesión con nombre + PIN",
  errTaken: "Ese nombre ya está en uso. Agregue un número.",
  errUsername: "El nombre debe tener de 3 a 20 letras o números, sin espacios.",
  errPin: "El PIN debe tener exactamente 6 números.",
  errLogin: "El nombre o el PIN no coinciden. Intente de nuevo.",
  inbox: "Bandeja",
  inboxIntro: "Aquí llegan las novedades de vivienda, empleos, pedidos y ayudantes. Léalas en la app o en cualquier kiosco.",
  inboxEmpty: "Nada todavía. Las novedades aparecerán aquí.",
  new: "Nuevo",
  open: "Abrir",
  bio: "Sobre usted",
  kioskInbox: "Mi bandeja",
  kioskInboxSub: "Inicie sesión con su nombre y PIN para ver sus novedades",
  kioskInboxWarn: "Toque Listo al terminar para que la siguiente persona no vea sus mensajes.",
  doneSignOut: "Listo (cerrar sesión)",
  getUpdatesTitle: "Reciba novedades sin teléfono",
  getUpdatesBody: "Cree una cuenta gratis solo con un nombre y un PIN de 6 dígitos. Las novedades de vivienda, respuestas de empleo y mensajes de ayudantes le esperarán en la app o en cualquier kiosco.",
  updatesOn: "Novedades activadas",
  updatesOnBody: "Este caso está guardado en su cuenta. Revise su bandeja en cualquier kiosco con su nombre y PIN.",
  appName: "Helping Hand",
  tagline: "Ayuda real, en su idioma, en su barrio.",
  homeQuestion: "¿Para quién busca ayuda hoy?",
  helpingSomeone: "Estoy ayudando a alguien",
  helpingSomeoneSub: "Consiga la ayuda correcta para una persona que conoció",
  helpingMyself: "Necesito ayuda",
  helpingMyselfSub: "Vivienda, comida, identificación, trabajo y más",
  jobs: "Empleos",
  jobsSub: "Consiga trabajo rápido",
  kiosk: "Kiosco",
  kioskSub: "Recogida de comida y ropa",
  helpers: "Ayudantes",
  helpersSub: "Voluntarios cerca",
  account: "Cuenta",
  signIn: "Iniciar sesión",
  signOut: "Cerrar sesión",
  language: "Idioma",
  next: "Siguiente",
  back: "Atrás",
  yes: "Sí",
  no: "No",
  skip: "Omitir",
  submit: "Ver mi plan de ayuda",
  optional: "opcional",
  call: "Llamar",
  whatToSay: "Qué decir cuando llame",
  hours: "Horario",

  stepOf: "Paso {a} de {b}",
  qName: "¿Cómo le llamamos?",
  qNameSomeone: "¿Cuál es el nombre de la persona?",
  qNameHint: "Nombre o apodo está bien.",
  qId: "¿Tiene una identificación del gobierno?",
  qIdSomeone: "¿Tiene la persona una identificación del gobierno?",
  qPhone: "¿Tiene teléfono?",
  qPhoneSomeone: "¿Tiene la persona un teléfono?",
  qSleep: "¿Tiene un lugar seguro para dormir esta noche?",
  qSleepSomeone: "¿Tiene la persona un lugar seguro para dormir esta noche?",
  urgentTitle: "Vamos a enviarle un trabajador de alcance",
  urgentBody:
    "No tiene que ir a un refugio. Miami-Dade envía trabajadores de alcance al área donde usted se queda para ayudarle a conseguir vivienda real (Realojamiento Rápido o Vivienda Permanente con Apoyo). No necesita una dirección exacta.",
  urgentBodySomeone:
    "No tiene que ir a un refugio. Miami-Dade envía trabajadores de alcance al área donde la persona se queda para ayudarle a conseguir vivienda real. No necesita saber exactamente dónde duerme.",
  qArea: "¿En qué zona se queda?",
  qAreaSomeone: "¿En qué zona suele quedarse la persona?",
  qAreaHint: "Un barrio, cruce de calles o punto de referencia es suficiente.",
  qLandmark: "Cruce de calles o punto de referencia",
  qLandmarkHint: "Ejemplo: cerca del Aldi en NE 108th St",
  qHowLong: "¿Cuánto tiempo lleva quedándose ahí?",
  qHowLongSomeone: "¿Cuánto tiempo lleva la persona quedándose ahí?",
  qPay: "¿Paga para quedarse ahí?",
  qPaySomeone: "¿Paga la persona para quedarse ahí?",
  qPayDetails: "¿Cuánto y a quién?",
  qNeeds: "¿Con qué necesita ayuda?",
  qNeedsSomeone: "¿Con qué necesita ayuda la persona?",
  qNeedsHint: "Marque todo lo que aplique.",
  allOfAbove: "Todo lo anterior",
  qContact: "¿Cómo puede contactarle un ayudante?",
  qContactSomeone: "¿Cómo puede contactarle a usted (quien ayuda) un ayudante?",
  qContactHint: "Teléfono o correo. Si no hay teléfono, díganos cuándo y dónde se le puede encontrar.",
  qNotes: "¿Algo más que debamos saber?",
  saving: "Guardando...",

  need_housing: "Vivienda",
  need_id: "Identificación",
  need_ssn: "Tarjeta del Seguro Social",
  need_food: "Comida",
  need_clothes: "Ropa",
  need_job: "Un trabajo",
  need_healthcare: "Atención médica",
  need_addiction: "Apoyo para adicciones",
  need_phone: "Un teléfono",

  dur_days: "Unos días",
  dur_weeks: "Unas semanas",
  dur_months: "Unos meses",
  dur_year: "Un año o más",

  planTitle: "Su plan de ayuda",
  planTitleSomeone: "Plan de ayuda para {name}",
  planIntro: "Aquí está a quién llamar para cada necesidad y qué decir. Un ayudante también puede acompañarle en persona.",
  yourNumber: "Su número de caso",
  showThis: "Muéstrelo en cualquier kiosco o a cualquier ayudante.",
  findHelper: "Conectarme con un ayudante cercano",
  findHelperSub: "Alguien de su zona que puede reunirse en persona y ayudar con llamadas, papeleo y transporte.",
  requestOutreach: "Solicitar un trabajador de alcance",
  outreachRequested: "Solicitud guardada. Llame a la línea de ayuda para asegurarse de que se abra hoy.",
  foodClothesNow: "¿Necesita comida o ropa ahora?",
  foodClothesNowSub: "Pida una recogida en el kiosco más cercano. Se empaca en nuestro almacén y llega en unos 20 minutos.",
  requestPickup: "Pedir recogida",
  seeJobs: "Ver empleos disponibles",
  noResources: "Todavía estamos agregando recursos para esta necesidad. Llame al 211 por ahora.",
  startOver: "Empezar de nuevo",

  helpersTitle: "Ayudantes cerca de usted",
  helpersIntro: "Estas personas se ofrecieron a reunirse en persona en su zona.",
  requestMatch: "Pedir reunión",
  matchSent: "Solicitud enviada. Le contactarán usando el contacto que dio.",
  noHelpers: "Aún no hay ayudantes en esta zona. Guardamos su solicitud y le conectaremos en cuanto alguien se una.",
  becomeHelper: "Ser ayudante",
  helperDash: "Panel de ayudante",
  openRequests: "Solicitudes abiertas en su zona",
  allAreas: "Todas las zonas",
  accept: "Puedo ayudar con esto",
  accepted: "Están conectados. Comuníquese usando el contacto de abajo.",
  noOpen: "No hay solicitudes abiertas ahora. Gracias por estar aquí.",

  jobsTitle: "Empleos disponibles",
  jobsIntro: "Los empleadores aquí saben que quizás aún no tenga identificación, dirección o teléfono. Busque las etiquetas verdes.",
  postJob: "Publicar empleo",
  apply: "Aplicar",
  applyTitle: "Aplicar a {title}",
  yourName: "Su nombre",
  yourContact: "Teléfono, correo o dónde encontrarle",
  message: "Mensaje (opcional)",
  sendApplication: "Enviar solicitud",
  applicationSent: "Enviada. El empleador se comunicará.",
  jobsSearch: "Buscar: lavaplatos, construcción, limpieza…",
  jobsAll: "Todos",
  jobsThisWeek: "Contratan esta semana",
  jobsNone: "Ningún empleo coincide. Pruebe otra palabra o quite los filtros.",
  tag_thisWeek: "Contratan esta semana",
  tag_noExp: "Sin experiencia ni diploma",
  cat_kitchen: "Restaurante y cocina",
  cat_construction: "Construcción",
  cat_cleaning: "Limpieza",
  cat_cafeteria: "Cafetería y comedor",
  cat_warehouse: "Almacén y mudanzas",
  cat_landscaping: "Jardinería",
  cat_hotel: "Hotel y limpieza de cuartos",
  tag_noId: "Sin identificación",
  tag_noAddress: "Sin dirección",
  tag_sameDay: "Pago el mismo día",
  jobTitle: "Puesto",
  company: "Empresa",
  pay: "Pago",
  jobType: "Tipo",
  description: "Descripción",
  requirements: "Requisitos",
  contactPhone: "Teléfono de contacto",
  contactEmail: "Correo de contacto",
  howToApply: "Cómo aplicar",
  publish: "Publicar",
  type_full_time: "Tiempo completo",
  type_part_time: "Medio tiempo",
  type_day_labor: "Jornal",
  type_gig: "Por encargo",
  type_temp: "Temporal",
  noJobs: "Aún no hay empleos publicados.",
  signInToPost: "Inicie sesión como empleador para publicar.",

  kioskTitle: "Bienvenido",
  kioskQuestion: "¿Necesita comida o ropa?",
  kioskYes: "Sí, necesito comida o ropa",
  kioskHelp: "Necesito otra ayuda",
  kioskStatus: "Ver mi pedido",
  kioskFood: "Comida",
  kioskClothes: "Ropa",
  kioskHygiene: "Kit de higiene",
  sizeTop: "Talla de camisa",
  sizeBottom: "Talla de pantalón",
  sizeShoes: "Talla de zapatos",
  kioskCode: "Su código de recogida",
  kioskArriving: "Se está empacando en el almacén. Llega a este kiosco en unos {n} minutos.",
  kioskShowCode: "Muestre este código cuando llegue la bolsa.",
  enterCode: "Escriba su código de recogida",
  check: "Ver",
  status_requested: "Recibido",
  status_packing: "Empacando",
  status_en_route: "En camino",
  status_delivered: "En el kiosco",
  status_picked_up: "Recogido",
  status_cancelled: "Cancelado",
  notFound: "Código no encontrado.",
  kioskPlace: "Pedir",

  email: "Correo",
  password: "Contraseña",
  displayName: "Nombre",
  role: "Soy",
  role_seeker: "Alguien que busca ayuda",
  role_helper: "Ayudante / voluntario",
  role_employer: "Empleador",
  role_driver: "Conductor / empacador",
  createAccount: "Crear cuenta",
  haveAccount: "¿Ya tiene cuenta? Inicie sesión",
  needAccount: "¿Nuevo aquí? Cree una cuenta",
  checkEmail: "Revise su correo para confirmar su cuenta y luego inicie sesión.",
  myArea: "Mi zona",
  canMeet: "Puedo reunirme en persona",
  helperSkills: "Puedo ayudar con",
  save: "Guardar",
  saved: "Guardado.",
  profile: "Perfil",
  driverDash: "Panel de conductor",
  deliveries: "Entregas",
  markPacking: "Empezar a empacar",
  markEnRoute: "En camino",
  markDelivered: "Entregado en kiosco",
  markPickedUp: "Recogido",
  minutesAgo: "hace {n} min",
  emergency: "Si alguien está en peligro ahora, llame al 911.",
  // --- Añadido en la revisión de diseño. COPIA NUEVA — pendiente de revisión. ---
  menu: "Menú",
  loading: "Cargando…",
  retry: "Intentar de nuevo",
  errGeneric: "Algo salió mal. No se perdió nada — inténtelo de nuevo.",
  errHelp: "Si sigue pasando, llame al 211. Es gratis, 24 horas, en su idioma.",
  privacyNote: "Solo compartimos lo que usted nos pide que compartamos. Puede parar cuando quiera.",
  areaLabel: "Zona",
};
