import type { Dict } from "./i18n";

export const en: Dict = {
  // intake v2 (case-worker order)
  qHousehold: "Is this for you alone, or for a family?",
  qHouseholdSomeone: "Is this one person, or a family?",
  qHouseholdHint: "Families with children get their own track and their own housing programs.",
  hhSingle: "Just me",
  hhSingleSomeone: "One person",
  hhSingleSub: "One adult",
  hhFamily: "My family",
  hhFamilySomeone: "A family or group",
  hhFamilySub: "Adults with children, a couple, or relatives together",
  qFamily: "Tell us about the family",
  qFamilySomeone: "Tell us about the family",
  adults: "Adults (18+)",
  children: "Children (under 18)",
  childrenAges: "Ages of the children",
  childrenAgesHint: "example: 3, 7, 12",
  qPregnant: "Is anyone pregnant?",
  qSenior: "Is anyone 60 or older?",
  qRegistrant: "Who is filling this out?",
  qRegistrantHint: "So the outreach worker knows who to call back.",
  relationship: "I am their",
  rel_friend: "Friend",
  rel_neighbor: "Neighbor",
  rel_family: "Family member",
  rel_caseworker: "Case worker",
  rel_volunteer: "Volunteer / helper",
  rel_other: "Other",
  qNameFamily: "What is the first name of the head of the family?",
  qNameFamilySomeone: "What is the first name of the head of the family?",
  qSleepFamily: "Does the family have a safe place to sleep tonight?",
  qSleepFamilySomeone: "Does the family have a safe place to sleep tonight?",
  qHomelessDuration: "How long have you been without a stable place?",
  qHomelessDurationSomeone: "How long have they been without a stable place?",
  hd_first: "This is the first time, less than a month",
  hd_months: "A few months",
  hd_year: "A year or more",
  hd_repeat: "Many times over the years",
  qDanger: "Is anyone hurting you or making you afraid right now?",
  qDangerSomeone: "Is anyone hurting them or making them afraid right now?",
  qDangerHint: "You can skip this. It only changes who we connect you with.",
  preferNot: "Prefer not to say",
  dangerNow: "You can get safe housing separate from everything else.",
  dangerBody: "Free, confidential, 24/7. Call or text START to 88788.",
  qDocuments: "Which papers do you have?",
  qDocumentsSomeone: "Which papers do they have?",
  qDocumentsHint: "No papers is normal. We will help get them, and it changes the order we do things in.",
  qSsn: "Social Security card (or you know the number)?",
  qSsnSomeone: "Social Security card (or they know the number)?",
  qBirthCert: "Birth certificate?",
  qBirthCertSomeone: "Birth certificate?",
  qIncome: "Is any money coming in?",
  qIncomeSomeone: "Is any money coming in?",
  qIncomeHint: "This decides which benefits you can get, not whether you get help.",
  inc_none: "No income",
  inc_job: "A job or day work",
  inc_ssi: "SSI / SSDI / Social Security",
  inc_other: "Something else",
  qSnap: "Getting SNAP / EBT food benefits now?",
  qSnapSomeone: "Getting SNAP / EBT food benefits now?",
  qMedicaid: "On Medicaid or other health insurance now?",
  qMedicaidSomeone: "On Medicaid or other health insurance now?",
  qHealth: "A few health questions",
  qHealthSomeone: "A few health questions",
  qHealthHint: "These open doors to disability money, veteran housing, and treatment. Skip anything you want.",
  qDisability: "A disability or ongoing condition that needs care?",
  qDisabilitySomeone: "A disability or ongoing condition that needs care?",
  qVeteran: "Ever served in the U.S. military?",
  qVeteranSomeone: "Ever served in the U.S. military?",
  qRecovery: "Would you like support with alcohol or drugs?",
  qRecoverySomeone: "Would they like support with alcohol or drugs?",
  qKids: "About the children",
  qKidsSchool: "Are the children enrolled in school?",
  qChildcare: "Is childcare needed so an adult can work or go to appointments?",
  kidsNote: "Children experiencing homelessness have a legal right to stay in their school with free transportation (McKinney-Vento). Ask the school for the homeless liaison.",
  qNeedsHintPre: "We checked what you told us. Add or remove anything.",
  familyOf: "Family of {n}",
  need_family: "Family housing & support",
  need_veterans: "Veteran services",
  need_safety: "Safety",
  need_general: "24/7 lines",
  // partners + donate
  partnerTitle: "Partner with us",
  partnerIntro: "Government, nonprofits, hospitals, dentists, businesses, foundations, churches: tell us what you can give and we will put it to work in the neighborhood that needs it.",
  partnerWhatWeNeed: "What we are asking for",
  partnerWhatWeNeedBody: "Kiosk locations and kiosk funding. Warehouse space. Vans or cars to move food and clothes. Drivers and packers (we hire program graduates). Food, clothing, hygiene kits, phones. Dental days and medical care. Help getting IDs, Social Security cards, EBT, Medicaid, and disability. Housing units. Jobs. Funding.",
  orgName: "Organization",
  orgType: "You are",
  org_government: "Government agency",
  org_nonprofit: "Nonprofit",
  org_hospital: "Hospital / clinic",
  org_dental: "Dentist / dental group",
  org_business: "Business",
  org_foundation: "Foundation / funder",
  org_faith: "Church / faith group",
  org_individual: "Individual",
  org_other: "Other",
  canOffer: "What can you offer?",
  offer_kiosk_site: "A kiosk location",
  offer_kiosk_funding: "Fund a kiosk",
  offer_warehouse: "Warehouse space",
  offer_vehicles: "Vehicles",
  offer_drivers: "Drivers / packers",
  offer_food: "Food",
  offer_clothes: "Clothing",
  offer_hygiene: "Hygiene kits",
  offer_phones: "Phones",
  offer_dental: "Dental care",
  offer_medical: "Medical care",
  offer_mental_health: "Mental health / recovery",
  offer_id_documents: "ID & documents help",
  offer_benefits_navigation: "EBT / Medicaid / disability help",
  offer_housing_units: "Housing units",
  offer_jobs: "Jobs",
  offer_funding: "Funding",
  offer_volunteers: "Volunteers",
  amountOrScale: "Amount or scale",
  amountHint: "e.g. $10,000, 2 vans, 20 dental visits a month, 500 sq ft",
  contactName: "Contact name",
  sendOffer: "Send offer",
  partnerThanks: "Thank you",
  partnerThanksBody: "We received your offer and will reach out within a few days.",
  individualDonate: "Not an organization? Donate as an individual",
  donateTitle: "Donate",
  donateIntro: "Every dollar, bag, and hour goes to someone in Miami-Dade who is getting back on their feet.",
  giveMoney: "Give money",
  giveMoneySub: "Funds kiosks, warehouse runs, phones, and documents",
  giveItems: "Give food, clothes, or hygiene items",
  giveItemsSub: "Drop off at a warehouse; we pack and deliver within 20 minutes of a request",
  giveTime: "Give time",
  giveTimeSub: "Become a helper who meets people in person",
  donateSoon: "Online giving is being set up. Leave your pledge below and we will send you the link.",
  pledgeAmount: "Pledge",
  sendPledge: "Send",
  itemsWanted: "Most needed: non-perishable food, new socks and underwear, men's clothing in L to 3XL, shoes, hygiene kits, backpacks, unlocked phones.",
  whatBringing: "What are you bringing?",
  dropoff: "Drop-off warehouse",
  timeBody: "Helpers meet people in their own area, make calls with them, ride along to appointments, and check the inbox for them. An hour a week changes a life.",
  donateThanks: "Thank you",
  donateThanksBody: "We received it. We will confirm by the contact you gave.",
  partnersHome: "Partners & donors",
  partnersHomeSub: "Give money, items, time, or services",
  need_benefits: "EBT / food & cash benefits",
  need_disability: "Disability (SSI / SSDI)",
  need_documents: "Documents & papers",
  close: "Close",
  flipCamera: "Flip",
  takePhoto: "Take photo",
  retake: "Retake",
  usePhoto: "Use photo",
  chooseFile: "Choose a file instead",
  cameraBlocked: "The camera is not available here. You can pick a photo or file instead.",
  photoLabelShort: "What is it? (optional)",
  rideRequest: "Need a ride? Request one",
  rideRequested: "Ride requested",
  rideAssigned: "Driver set",
  rideEnRoute: "Driver on the way",
  ridePickedUp: "On the way",
  rideDone: "Ride done",
  rideCancelled: "Ride cancelled",
  rideNoShow: "Missed pickup",
  rideCancel: "Cancel ride",
  rides: "Rides",
  rideFrom: "Pickup",
  rideTo: "Going to",
  rideMarkAssigned: "I will take it",
  rideMarkEnRoute: "On my way",
  rideMarkPickedUp: "Picked up",
  rideMarkDone: "Dropped off",
  rideMarkNoShow: "No show",
  rideDest_fl_id: "Miami-Dade FLHSMV / Tax Collector office",
  rideDest_ssn_card: "Social Security office",
  rideDest_birth_cert: "Vital Statistics office",
  rideDest_benefits: "DCF ACCESS interview",
  home: "Home",
  benefitsShort: "Benefits",
  docsHomeShort: "ID, Social Security card, birth certificate, EBT",
  hubTitle: "Benefits, documents & healthcare",
  hubSub: "EBT, Medicaid, disability, government housing, birth certificate, ID",
  hubIntro: "Everything you need to get set up, in one place. Tap a topic to see who to call, what to say, and what to bring. Most of these can be done with no fixed address.",
  hubWhatToBring: "Start here if you have no papers",
  hubWhatToBringBody: "Step 1: get a mailing address (Camillus House Day Center or an outreach agency). Step 2: Social Security card (free). Step 3: birth certificate. Step 4: Florida ID (fee waived if homeless). With those three, you can apply for EBT, Medicaid, disability, housing, and jobs.",
  // pin accounts + inbox
  signInIntro: "No email or phone needed. Pick a name and a 6-digit PIN. That is your account.",
  username: "Your name (one word)",
  usernameHint: "example: marcus1990",
  pin: "6-digit PIN",
  pinHint: "Pick 6 numbers you will remember. Do not share them.",
  useEmail: "Staff: sign in with email instead",
  usePin: "Sign in with name + PIN",
  errTaken: "That name is taken. Try adding a number.",
  errUsername: "Name must be 3 to 20 letters or numbers, no spaces.",
  errPin: "PIN must be exactly 6 numbers.",
  errLogin: "Name or PIN did not match. Try again.",
  inbox: "Inbox",
  inboxIntro: "Updates about housing, jobs, pickups, and helpers come here. Read them in the app or at any kiosk.",
  inboxEmpty: "Nothing yet. Updates will show up here.",
  new: "New",
  open: "Open",
  bio: "About you",
  kioskInbox: "My inbox",
  kioskInboxSub: "Sign in with your name and PIN to see your updates",
  kioskInboxWarn: "Tap Done when you finish so the next person cannot see your messages.",
  doneSignOut: "Done (sign out)",
  getUpdatesTitle: "Get updates without a phone",
  getUpdatesBody: "Make a free account with just a name and a 6-digit PIN. Housing updates, job replies, and helper messages will wait for you in the app or at any kiosk.",
  updatesOn: "Updates are on",
  updatesOnBody: "This case is saved to your account. Check your inbox at any kiosk with your name and PIN.",
  appName: "Helping Hand",
  tagline: "Real help, in your language, in your neighborhood.",
  homeQuestion: "Who are you here for today?",
  helpingSomeone: "I'm helping someone",
  helpingSomeoneSub: "Get a person you met the right help",
  helpingMyself: "I need help",
  helpingMyselfSub: "Housing, food, ID, a job, and more",
  jobs: "Jobs",
  jobsSub: "Get hired fast",
  kiosk: "Kiosk",
  kioskSub: "Food & clothes pickup",
  helpers: "Helpers",
  helpersSub: "Volunteer nearby",
  account: "Account",
  signIn: "Sign in",
  signOut: "Sign out",
  language: "Language",
  next: "Next",
  back: "Back",
  yes: "Yes",
  no: "No",
  skip: "Skip",
  submit: "Get my help plan",
  optional: "optional",
  call: "Call",
  whatToSay: "What to say when you call",
  hours: "Hours",

  // intake
  stepOf: "Step {a} of {b}",
  qName: "What should we call you?",
  qNameSomeone: "What is the person's first name?",
  qNameHint: "First name or nickname is fine.",
  qId: "Do you have a government ID?",
  qIdSomeone: "Do they have a government ID?",
  qPhone: "Do you have a phone?",
  qPhoneSomeone: "Do they have a phone?",
  qSleep: "Do you have a safe place to sleep tonight?",
  qSleepSomeone: "Do they have a safe place to sleep tonight?",
  urgentTitle: "Let's get an outreach worker to you",
  urgentBody:
    "You do not need to go to a shelter. Miami-Dade sends street outreach workers to the area where you stay to help you get real housing (Rapid Re-Housing or Permanent Supportive Housing). You do not need an exact address.",
  urgentBodySomeone:
    "They do not need to go to a shelter. Miami-Dade sends street outreach workers to the area where the person stays to help them get real housing. You do not need to know exactly where they sleep.",
  qArea: "What area do you stay in?",
  qAreaSomeone: "What area do they usually stay in?",
  qAreaHint: "A neighborhood, cross street, or landmark is enough.",
  qLandmark: "Cross street or landmark",
  qLandmarkHint: "Example: near the Aldi on NE 108th St",
  qHowLong: "How long have you been staying there?",
  qHowLongSomeone: "How long have they been staying there?",
  qPay: "Do you pay to stay there?",
  qPaySomeone: "Do they pay to stay there?",
  qPayDetails: "How much, and to whom?",
  qNeeds: "What do you need help with?",
  qNeedsSomeone: "What do they need help with?",
  qNeedsHint: "Pick everything that applies.",
  allOfAbove: "All of the above",
  qContact: "How can a helper reach you?",
  qContactSomeone: "How can a helper reach you (the person helping)?",
  qContactHint: "Phone or email. If there is no phone, tell us when and where you can be found.",
  qNotes: "Anything else we should know?",
  saving: "Saving...",

  // needs
  need_housing: "Housing",
  need_id: "ID",
  need_ssn: "Social Security card",
  need_food: "Food",
  need_clothes: "Clothes",
  need_job: "A job",
  need_healthcare: "Healthcare",
  need_addiction: "Addiction support",
  need_phone: "A phone",

  // durations
  dur_days: "A few days",
  dur_weeks: "A few weeks",
  dur_months: "A few months",
  dur_year: "A year or more",

  // results
  planTitle: "Your help plan",
  planTitleSomeone: "Help plan for {name}",
  planIntro: "Here is who to call for each thing you need, and what to say. A helper can also walk through this with you in person.",
  yourNumber: "Your case number",
  showThis: "Show this at any kiosk or to any helper.",
  findHelper: "Match me with a helper nearby",
  findHelperSub: "Someone in your area who can meet you in person and help with calls, paperwork, and rides.",
  requestOutreach: "Request a street outreach worker",
  outreachRequested: "Outreach request saved. Call the helpline below to make sure it is opened today.",
  foodClothesNow: "Need food or clothes right now?",
  foodClothesNowSub: "Request a pickup at the nearest kiosk. It is packed at our warehouse and delivered in about 20 minutes.",
  requestPickup: "Request a pickup",
  seeJobs: "See jobs hiring now",
  noResources: "We are still adding resources for this need. Call 211 for now.",
  startOver: "Start over",

  // helpers
  helpersTitle: "Helpers near you",
  helpersIntro: "These people volunteered to meet in person in your area.",
  requestMatch: "Ask to meet",
  matchSent: "Request sent. They will reach out using the contact you gave.",
  noHelpers: "No helpers in this area yet. We saved your request and will match you as soon as someone joins.",
  becomeHelper: "Become a helper",
  helperDash: "Helper dashboard",
  openRequests: "Open requests in your area",
  allAreas: "All areas",
  accept: "I can help with this",
  accepted: "You are matched. Reach out using the contact below.",
  noOpen: "No open requests right now. Thank you for being here.",

  // jobs
  jobsTitle: "Jobs hiring now",
  jobsIntro: "Employers here know you may not have an ID, an address, or a phone yet. Look for the green tags.",
  postJob: "Post a job",
  apply: "Apply",
  applyTitle: "Apply for {title}",
  yourName: "Your name",
  yourContact: "Phone, email, or where to find you",
  message: "Message (optional)",
  sendApplication: "Send application",
  applicationSent: "Sent. The employer will reach out.",
  jobsSearch: "Search: dishwasher, construction, cleaning…",
  jobsAll: "All jobs",
  jobsThisWeek: "Hiring this week",
  jobsNone: "No jobs match. Try another word or clear the filters.",
  tag_thisWeek: "Hiring this week",
  tag_noExp: "No experience or diploma needed",
  cat_kitchen: "Restaurant & kitchen",
  cat_construction: "Construction",
  cat_cleaning: "Cleanup & cleaning",
  cat_cafeteria: "Cafeteria & food service",
  cat_warehouse: "Warehouse & moving",
  cat_landscaping: "Landscaping",
  cat_hotel: "Hotel & housekeeping",
  tag_noId: "No ID needed",
  tag_noAddress: "No address needed",
  tag_sameDay: "Same-day pay",
  jobTitle: "Job title",
  company: "Company",
  pay: "Pay",
  jobType: "Type",
  description: "Description",
  requirements: "Requirements",
  contactPhone: "Contact phone",
  contactEmail: "Contact email",
  howToApply: "How to apply",
  publish: "Publish job",
  type_full_time: "Full time",
  type_part_time: "Part time",
  type_day_labor: "Day labor",
  type_gig: "Gig",
  type_temp: "Temporary",
  noJobs: "No jobs posted yet.",
  signInToPost: "Sign in as an employer to post a job.",

  // kiosk
  kioskTitle: "Welcome",
  kioskQuestion: "Do you need food or clothes?",
  kioskYes: "Yes, I need food or clothes",
  kioskHelp: "I need other help",
  kioskStatus: "Check my pickup",
  kioskFood: "Food",
  kioskClothes: "Clothes",
  kioskHygiene: "Hygiene kit",
  sizeTop: "Shirt size",
  sizeBottom: "Pants size",
  sizeShoes: "Shoe size",
  kioskCode: "Your pickup code",
  kioskArriving: "Being packed at the warehouse. Arriving at this kiosk in about {n} minutes.",
  kioskShowCode: "Show this code when the bag arrives.",
  enterCode: "Enter your pickup code",
  check: "Check",
  status_requested: "Received",
  status_packing: "Packing",
  status_en_route: "On the way",
  status_delivered: "At the kiosk",
  status_picked_up: "Picked up",
  status_cancelled: "Cancelled",
  notFound: "Code not found.",
  kioskPlace: "Order",

  // account
  email: "Email",
  password: "Password",
  displayName: "Name",
  role: "I am",
  role_seeker: "Looking for help",
  role_helper: "A helper / volunteer",
  role_employer: "An employer",
  role_driver: "A driver / packer",
  createAccount: "Create account",
  haveAccount: "Already have an account? Sign in",
  needAccount: "New here? Create an account",
  checkEmail: "Check your email to confirm your account, then sign in.",
  myArea: "My area",
  canMeet: "I can meet people in person",
  helperSkills: "I can help with",
  save: "Save",
  saved: "Saved.",
  profile: "Profile",
  driverDash: "Driver dashboard",
  deliveries: "Deliveries",
  markPacking: "Start packing",
  markEnRoute: "On the way",
  markDelivered: "Delivered to kiosk",
  markPickedUp: "Picked up",
  minutesAgo: "{n} min ago",
  emergency: "If someone is in danger right now, call 911.",
  // --- Added in the polish pass. NEW COPY — needs Charlotte's review in ES / HT. ---
  menu: "Menu",
  loading: "Loading…",
  retry: "Try again",
  errGeneric: "Something went wrong. Nothing was lost — please try again.",
  errHelp: "If it keeps happening, call 211. It is free, 24 hours, in your language.",
  privacyNote: "We only share what you tell us to share. You can stop at any time.",
  areaLabel: "Area",
};
